name: common_code_persistence
version: 0.0.1
publish_to: 'none'
environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  common_code_application:
    path: ../common_code_application
  common_code_domain:
    path: ../common_code_domain
  shared_preferences: ^2.2.0

dev_dependencies:
  test: ^1.25.6
