name: host_opencode
version: 1.0.0
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  meta: ^1.15.0
  common_code_domain:
    path: ../common_code_domain
  common_code_application:
    path: ../common_code_application
dev_dependencies:
  flutter_test:
    sdk: flutter
